# Generated by Django 2.1.2 on 2018-10-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='participants',
            field=models.CharField(choices=[('Alex', 'Alex'), ('Helen', 'Helen'), ('Nick', 'Nick'), ('admin', 'admin')], max_length=100),
        ),
    ]
