# Generated by Django 2.1.2 on 2018-11-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20181101_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='participants',
            field=models.CharField(choices=[('Alex', 'Alex'), ('Andrey', 'Andrey'), ('Helen', 'Helen'), ('Nick', 'Nick'), ('admin', 'admin')], max_length=100),
        ),
    ]
