# Generated by Django 2.1.2 on 2018-11-01 13:03

import django.contrib.auth.models
from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20181101_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='participants',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(2, 'Alex'), (5, 'Andrey'), (3, 'Helen'), (4, 'Nick'), (1, 'admin')], default=django.contrib.auth.models.User, max_length=100),
        ),
    ]
