# Generated by Django 2.1.2 on 2018-11-14 17:51

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20181109_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entry',
            name='participants',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('', ''), ('Alex', 'Alex'), ('Andrey', 'Andrey'), ('Helen', 'Helen'), ('Mark', 'Mark'), ('Nick', 'Nick'), ('a', 'a'), ('aa', 'aa'), ('admin', 'admin'), ('user', 'user'), ('user1', 'user1')], default=django.contrib.auth.models.User, max_length=100),
        ),
    ]
